<?php if ( $this->get_session_data( 'license' ) ) { ?>
<a class="btn btn-primary btn-block" href="<?php echo htmlspecialchars( $this->link( 'customers', 'licenses' ) ); ?>">Change license</a>
<a class="btn btn-primary btn-block" href="<?php echo htmlspecialchars( $this->link( 'customers', 'websites' ) ); ?>">Add website</a>
<?php } else { ?>
<a class="btn btn-primary btn-block" href="<?php echo htmlspecialchars( $this->link( 'customers', 'licenses' ) ); ?>">Buy license</a>
<?php } ?>
